# Generated by Django 4.0.3 on 2022-07-19 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComfyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('catalog_visiblity', models.CharField(default='visible', max_length=100)),
                ('description', models.CharField(blank=True, max_length=340, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='products')),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('item_type', models.PositiveSmallIntegerField(choices=[(1, 't_shirts'), (2, 'trouser'), (3, 'skirt'), (4, 'dress'), (5, 'accesory'), (6, 'toys'), (7, 'bag')], null=True)),
                ('prod_category', models.PositiveSmallIntegerField(choices=[(1, 'womens'), (2, 'mens'), (3, 'kids')], null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComfySale',
            fields=[
                ('comfy_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.comfyproducts')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_on_sale_from', models.DateTimeField(null=True)),
                ('date_on_sale_from_gmt', models.DateTimeField(null=True)),
                ('date_on_sale_to', models.DateTimeField(null=True)),
                ('date_on_sale_to_gmt', models.DateTimeField(null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('purchasable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('comfy_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.comfyproducts')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('width', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('comfy_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.comfyproducts')),
                ('shipping_required', models.BooleanField(default=False, null=True)),
                ('shipping_taxable', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, null=True, upload_to='products')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('comfy_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.comfyproducts')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSizeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(choices=[(1, 'XL'), (2, 'XXL'), (3, 'S'), (4, 'L')], null=True)),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'Red'), (2, 'Green'), (3, 'White'), (4, 'Blue'), (5, 'Silver')], null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.comfyproducts')),
            ],
            options={
                'unique_together': {('color', 'size')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wished_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.comfyproducts')),
            ],
            options={
                'db_table': 'favorite',
                'unique_together': {('wished_item', 'user_id')},
            },
        ),
    ]
