# Generated by Django 4.0.3 on 2022-03-12 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComfyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_created_gmt', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('date_modified_gmt', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='simple', max_length=255)),
                ('status', models.CharField(default='publish', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('catalog_visiblity', models.CharField(default='visible', max_length=100)),
                ('description', models.CharField(blank=True, max_length=340, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(default='wp_pennant', max_length=100)),
                ('regular_price', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComfySale',
            fields=[
                ('comfy_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.comfyproducts')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_on_sale_from', models.DateTimeField(null=True)),
                ('date_on_sale_from_gmt', models.DateTimeField(null=True)),
                ('date_on_sale_to', models.DateTimeField(null=True)),
                ('date_on_sale_to_gmt', models.DateTimeField(null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('purchasable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('comfy_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.comfyproducts')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('width', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('comfy_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.comfyproducts')),
                ('shipping_required', models.BooleanField(default=False, null=True)),
                ('shipping_taxable', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(blank=True, null=True, upload_to='products')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('comfy_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.comfyproducts')),
            ],
        ),
        migrations.AlterField(
            model_name='itemsizecolor',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.comfyproducts'),
        ),
    ]
