# Generated by Django 4.0.3 on 2022-08-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comfyproducts',
            name='item_type',
            field=models.CharField(choices=[('dress', 'dress'), ('jumpsuit', 'jumpsuit'), ('two_piece_clothes', 'two_piece_clothes'), ('women_suit', 'women_suit'), ('pajamas', 'pajamas'), ('women_blazer', 'women_blazer'), ('top', 'top'), ('skirt', 'skirt'), ('accesory', 'accesory'), ('bag', 'bag'), ('women_trouser', 'women_trouser'), ('t_shirt', 't_shirt'), ('trouser', 'trouser'), ('watch', 'watch'), ('toys', 'toys'), ('kids_bag', 'kids_bag')], max_length=50, null=True),
        ),
    ]
