# Generated by Django 4.0.3 on 2022-05-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_favoriteproduct_index_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproduct',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
