# Generated by Django 4.0.3 on 2022-03-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comfyproducts_prod_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comfyproducts',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
