# Generated by Django 4.0.3 on 2022-05-10 20:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_favoriteproduct_status'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='favoriteproduct',
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproduct',
            unique_together={('wished_item', 'user_id')},
        ),
    ]
