# Generated by Django 4.0.3 on 2022-03-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_comfyproducts_regular_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comfyproducts',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
