# Generated by Django 4.0.3 on 2022-04-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comfyproducts',
            name='item_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 't_shirts'), (2, 'trouser'), (3, 'skirt'), (4, 'dress'), (5, 'accesory'), (6, 'toys'), (7, 'bag')], null=True),
        ),
    ]
