# Generated by Django 4.0.3 on 2022-03-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_title', models.CharField(max_length=255)),
                ('prod_description', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('price_updated_at', models.DateTimeField(blank=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('length', models.DecimalField(decimal_places=3, max_digits=5)),
                ('height', models.DecimalField(decimal_places=3, max_digits=5)),
                ('width', models.DecimalField(decimal_places=3, max_digits=3)),
                ('brand', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
