# Generated by Django 4.0.3 on 2022-03-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_height_alter_products_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
