# Generated by Django 4.0.3 on 2022-03-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comfyproducts_comfysale_dimension_shippinginfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comfyproducts',
            name='prod_category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'womens'), (2, 'mens'), (3, 'kids')], null=True),
        ),
    ]
