# Generated by Django 4.0.3 on 2022-04-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comfyproducts_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.RemoveField(
            model_name='comfyproducts',
            name='date_created_gmt',
        ),
        migrations.RemoveField(
            model_name='comfyproducts',
            name='date_modified_gmt',
        ),
        migrations.RemoveField(
            model_name='comfyproducts',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='comfyproducts',
            name='status',
        ),
        migrations.AddField(
            model_name='comfyproducts',
            name='item_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 't_shirts'), (2, 'trouser'), (3, 'skirt'), (4, 'dress'), (5, 'accesory'), (6, 'toys')], null=True),
        ),
        migrations.AlterField(
            model_name='comfyproducts',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
